// AUTO-GENERATED -- SYNCED FROM THE PRIVATE MONOREPO. DO NOT EDIT BY HAND.
//
// Ambient companion to ./index.d.ts for @getoverflow/payment-elements/types.
// See packages/payment-elements-v1/scripts/build-dts.mjs in the monorepo.
//
// Generated by build:dts; do not edit by hand.
// Ambient Window.Overflow types for script-tag and CMS integrators.
interface Window {
  Overflow: import('./index.js').OverflowConstructor;
}
